export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_REQ_START = 'SIGNUP_REQ_START';
export const SIGNUP_REQ_SUCCESS = 'SIGNUP_REQ_SUCCESS';
export const SIGNUP_REQ_FAILURE = 'SIGNUP_FAILURE';
export const TOKEN_REQ_START = 'TOKEN_REQ_START';
export const TOKEN_REQ_SUCCESS = 'TOKEN_REQ_SUCESS';
export const TOKEN_REQ_FAILURE = 'TOKEN_REQ_FAILURE';

export const TOKEN_MISSING_ERROR = 'TOKEN_MISSING_ERROR';
export const CREATE_MAINT_FAILURE = 'CREATE_MAINT_FAILURE';
export const CREATE_MAINT_REQ_START = 'CREATE_MAINT_REQ_START';
export const CREATE_MAINT_SUCCESS = 'CREATE_MAINT_SUCCESS';

export const GET_DISTANCE_START = 'GET_DISTANCE_START';
export const GET_DISTANCE_FAILURE = 'GET_DISTANCE_FAILURE';
export const GET_DISTANCE_SUCCESS = 'GET_DISTANCE_SUCCESS';

export const BIKE_REQ_START = 'BIKE_REQ_START';
export const BIKE_REQ_FAILURE = 'BIKE_REQ_FAILURE';
export const BIKE_REQ_SUCCESS = 'BIKE_REQ_SUCCESS';

export const GET_ALL_EVENTS_START = 'GET_ALL_EVENTS_START';
export const GET_ALL_EVENTS_FAILURE = 'GET_ALL_EVENTS_FAILURE';
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
