"""empty message

Revision ID: a5d9cbbe01ea
Revises: None
Create Date: 2016-11-20 12:15:51.129806

"""

# revision identifiers, used by Alembic.
revision = 'a5d9cbbe01ea'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('maintenance_event', 'bike_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_event', 'bike_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bike', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
