"""empty message

Revision ID: e21e02ad6181
Revises: a5d9cbbe01ea
Create Date: 2016-12-12 21:19:59.842278

"""

# revision identifiers, used by Alembic.
revision = 'e21e02ad6181'
down_revision = 'a5d9cbbe01ea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('types', postgresql.ARRAY(String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_type')
    ### end Alembic commands ###
